# 本节课内容大纲
## Python数据结构
### list, 数字, 字符串，字典，元组，时间和日期
## Python 函数
### 参数，return语句
## Python 模块
## Numpy
### 数据类型，数组属性，从已有的数组创建数组，从数值范围创建数组，切片和索引，广播，迭代数组
## 项目案例：怎么给孩子取名

# Python数据结构

## Python列表（list）

### 序列是Python中最基本的数据结构。序列中的每个元素都分配一个数字 - 它的位置，或索引，第一个索引是0，第二个索引是1，依此类推。
### 序列都可以进行的操作包括索引，切片，加，乘，检查成员。

In [1]:
list1 = ['Google', 'Runoob', 1997, 2000]
list2 = [1, 2, 3, 4, 5 ]
list3 = ["a", "b", "c", "d"]

In [3]:
print ("list1[0]: ", list1[0])
print ("list2[1:4]: ", list2[1:4])

list1[0]:  Google
list2[1:4]:  [2, 3, 4]


### 更新列表

In [4]:
list = ['Google', 'Runoob', 1997, 2000]
 
print ("第三个元素为 : ", list[2])
list[2] = 2001
print ("更新后的第三个元素为 : ", list[2])

第三个元素为 :  1997
更新后的第三个元素为 :  2001


### 删除列表元素

In [5]:
list = ['Google', 'Runoob', 1997, 2000]
 
print ("原始列表 : ", list)
del list[2]
print ("删除第三个元素 : ", list)

原始列表 :  ['Google', 'Runoob', 1997, 2000]
删除第三个元素 :  ['Google', 'Runoob', 2000]


### Python列表脚本操作符

In [6]:
len([1,2,3])

3

In [7]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [8]:
['Hi!'] * 4

['Hi!', 'Hi!', 'Hi!', 'Hi!']

In [9]:
3 in [1, 2, 3]

True

In [11]:
for x in [1, 2, 3]: 
    print(x)

1
2
3


### 嵌套列表

In [12]:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
print(x)

[['a', 'b', 'c'], [1, 2, 3]]


In [13]:
print(x[0])

['a', 'b', 'c']


In [14]:
print(x[0][0])

a


## Python 数字(Number)

### 整型(Int) - 通常被称为是整型或整数，是正或负整数，不带小数点。Python3 整型是没有限制大小的，可以当作 Long 类型使用，所以 Python3 没有 Python2 的 Long 类型。
### 浮点型(float) - 浮点型由整数部分与小数部分组成，浮点型也可以使用科学计数法表示（2.5e2 = 2.5 x 102 = 250）
### 复数( (complex)) - 复数由实数部分和虚数部分构成，可以用a + bj,或者complex(a,b)表示， 复数的实部a和虚部b都是浮点型。

In [17]:
a = 3
b = 4.0
c = 2.14j
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'complex'>


### Python 数字类型转换

#### int(x) 将x转换为一个整数。
#### float(x) 将x转换到一个浮点数。

In [19]:
a = 1.5
int(a)

1

### 数学函数

In [22]:
import math

In [35]:
print(abs(-2))
print(math.exp(3))
print(pow(2,3))
print(math.sqrt(4))
print(min(1,2,3))
print(max(2,3,4))

2
20.085536923187668
8
2.0
1
4


## Python 字符串

In [66]:
var1 = 'Hello World!'
var2 = "Mac"
print(var1,var2)
print ("var1[0]: ", var1[0])
print ("var2[1:5]: ", var2[1:])

Hello World! Mac
var1[0]:  H
var2[1:5]:  ac


### Python 字符串更新

In [64]:
var1 = 'Hello World!'
 
print ("已更新字符串 : ", var1[:6] + 'Mac!')

已更新字符串 :  Hello Mac!


### Python转义字符

![jupyter](./1.png)

In [3]:
a = 'asd\n123'
print(a)

asd
123


### Python字符串格式化

![jupyter](./2.png)

In [4]:
print ("我叫 %s 今年 %d 岁!" % ('小明', 10))

我叫 小明 今年 10 岁!


## Python 字典 (Dictionary)

### 字典是另一种可变容器模型，且可存储任意类型对象。
### 字典的每个键值 key=>value 对用冒号 : 分割，每个键值对之间用逗号 , 分割，整个字典包括在花括号 {} 中。

In [3]:
dict = {'a': 1, 'b': '3'}
print(dict['b'])
print(dict.keys())
print(dict.values())

3
dict_keys(['a', 'b'])
dict_values([1, '3'])


In [4]:
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
 
print ("dict['Name']: ", dict['Name'])
print ("dict['Age']: ", dict['Age'])

dict['Name']:  Zara
dict['Age']:  7


### 修改字典

### 向字典添加新内容的方法是增加新的键/值对，修改或删除已有键/值对如下实例:

In [68]:
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
 
dict['Age'] = 8 # 更新
dict['School'] = "XJTLU" # 添加
 

print ("dict['Age']: ", dict['Age'])
print ("dict['School']: ", dict['School'])

dict['Age']:  8
dict['School']:  XJTLU


### 删除字典元素

### 能删单一的元素也能清空字典，清空只需一项操作。
### 显示删除一个字典用del命令，如下实例：

In [71]:
dict1 = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
 
del dict1['Name']  # 删除键是'Name'的条目
print ("dict1['Age']:", dict1['Age']) 
dict1.clear()      # 清空字典所有条目
print ("dict1['Age']:", dict1['Age']) 
del dict1          # 删除字典
print ("dict1['Age']:", dict1['Age']) 

dict1['Age']: 7


KeyError: 'Age'

## Python元组 (tuple)

### Python的元组与列表类似，不同之处在于元组的元素不能修改。
### 元组使用小括号，列表使用方括号。
### 元组创建很简单，只需要在括号中添加元素，并使用逗号隔开即可。

In [16]:
tup1 = ('physics', 'chemistry', 1997, 2000)
tup2 = (1, 2, 3, 4, 5, 6, 7 )
 
print ("tup1[0]: ", tup1[0])
print ("tup2[1:5]: ", tup2[1:5])

tup1[0]:  physics
tup2[1:5]:  (2, 3, 4, 5)


### 元组中的元素值是不允许修改的，但我们可以对元组进行连接组合，如下实例:

In [17]:
tup1 = (12, 34.56)
tup2 = ('abc', 'xyz')
 
# 以下修改元组元素操作是非法的。
# tup1[0] = 100
 
# 创建一个新的元组
tup3 = tup1 + tup2
print (tup3)

(12, 34.56, 'abc', 'xyz')


### 元组中的元素值是不允许删除的，但我们可以使用del语句来删除整个元组，如下实例:

In [18]:
tup = ('physics', 'chemistry', 1997, 2000)
 
print (tup)
del tup
print ("After deleting tup : ")
print (tup)

('physics', 'chemistry', 1997, 2000)
After deleting tup : 


NameError: name 'tup' is not defined

### 元组索引，截取

In [20]:
L = ('spam', 'Spam', 'SPAM!')
print(L[2])
print(L[-2])
print(L[1:])

SPAM!
Spam
('Spam', 'SPAM!')


## Python时间和日期

Python 程序能用很多方式处理日期和时间，转换日期格式是一个常见的功能。

Python 提供了一个 time 和 calendar 模块可以用于格式化日期和时间。

每个时间戳都以自从1970年1月1日午夜（历元）经过了多长时间来表示。

时间间隔是以秒为单位的浮点小数。

In [76]:
import time   # 引入time模块
 
ticks = time.time()
print ("当前时间戳为:", ticks)

当前时间戳为: 1595755073.578018


In [82]:
localtime = time.localtime()
print ("本地时间为 :", localtime)

本地时间为 : time.struct_time(tm_year=2020, tm_mon=7, tm_mday=26, tm_hour=17, tm_min=22, tm_sec=24, tm_wday=6, tm_yday=208, tm_isdst=0)


### 格式化日期
我们可以使用 time 模块的 strftime 方法来格式化日期，：

In [79]:
ti = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
print (ti )
print(type(ti))

2020-07-26 17:21:46
<class 'str'>


In [80]:
print (time.strftime("%a %b %d %H:%M:%S %Y", time.localtime())) 

Sun Jul 26 17:22:01 2020


### python中时间日期格式化符号：

%y 两位数的年份表示（00-99）

%Y 四位数的年份表示（000-9999）

%m 月份（01-12）

%d 月内中的一天（0-31）

%H 24小时制小时数（0-23）

%I 12小时制小时数（01-12）

%M 分钟数（00-59）

%S 秒（00-59）

%a 本地简化星期名称

%A 本地完整星期名称

%b 本地简化的月份名称

%B 本地完整的月份名称

%c 本地相应的日期表示和时间表示

%j 年内的一天（001-366）

%p 本地A.M.或P.M.的等价符

%U 一年中的星期数（00-53）星期天为星期的开始

%w 星期（0-6），星期天为星期的开始

%W 一年中的星期数（00-53）星期一为星期的开始

%x 本地相应的日期表示

%X 本地相应的时间表示

%Z 当前时区的名称

%% %号本身

### 获取某月日历

In [83]:
import calendar
 
cal = calendar.month(2020, 1)
print ("以下输出2020年1月份的日历:")
print (cal)

以下输出2020年1月份的日历:
    January 2020
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31



### datetime是Python处理日期和时间的标准库。

In [36]:
from datetime import datetime
now = datetime.now()
print(now)
print(type(now))

2020-07-10 16:32:32.558022
<class 'datetime.datetime'>


注意到datetime是模块，datetime模块还包含一个datetime类，通过from datetime import datetime导入的才是datetime这个类。
如果仅导入import datetime，则必须引用全名datetime.datetime。

In [38]:
from datetime import datetime
dt = datetime(2020, 4, 19, 12, 20) # 用指定日期时间创建datetime
print(dt)
print(type(dt))

2020-04-19 12:20:00
<class 'datetime.datetime'>


把一个datetime类型转换为timestamp只需要简单调用timestamp()方法：

In [40]:
from datetime import datetime
dt = datetime(2015, 4, 19, 12, 20) # 用指定日期时间创建datetime
dt = dt.timestamp() # 把datetime转换为timestamp
print(dt)
print(type(dt))

1429417200.0
<class 'float'>


### timestamp转换为datetime

要把timestamp转换为datetime，使用datetime提供的fromtimestamp()方法：

In [41]:
from datetime import datetime
t = 1429417200.0
print(datetime.fromtimestamp(t))

2015-04-19 12:20:00


### str转换为datetime

In [43]:
from datetime import datetime
cday = datetime.strptime('2015-6-1 18:19:59', '%Y-%m-%d %H:%M:%S')
print(cday)
print(type(cday))

2015-06-01 18:19:59
<class 'datetime.datetime'>


### datetime转换为str

In [45]:
from datetime import datetime
now = datetime.now()
now = now.strftime('%a, %b %d %H:%M')
print(now)
print(type(now))

Fri, Jul 10 17:01
<class 'str'>


### datetime加减

In [48]:
from datetime import datetime, timedelta
now = datetime.now()
print(now)
print(now + timedelta(hours=10))
print(now - timedelta(days=1))
print(now + timedelta(days=2, hours=12))

2020-07-10 17:20:46.089386
2020-07-11 03:20:46.089386
2020-07-09 17:20:46.089386
2020-07-13 05:20:46.089386


# Python函数

函数是组织好的，可重复使用的，用来实现单一，或相关联功能的代码段。
函数能提高应用的模块性，和代码的重复利用率。你已经知道Python提供了许多内建函数，比如print()。但你也可以自己创建函数，这被叫做用户自定义函数。

## 定义一个函数
你可以定义一个由自己想要功能的函数，以下是简单的规则：

函数代码块以 def 关键词开头，后接函数标识符名称和圆括号()。

任何传入参数和自变量必须放在圆括号中间。圆括号之间可以用于定义参数。

函数的第一行语句可以选择性地使用文档字符串—用于存放函数说明。

函数内容以冒号起始，并且缩进。

return [表达式] 结束函数，选择性地返回一个值给调用方。不带表达式的return相当于返回 None。

In [51]:
def hello() :
    print("Hello World!")

hello()

Hello World!


In [52]:
# 计算面积函数
def area(width, height):
    return width * height
 
def print_welcome(name):
    print("Welcome", name)

print_welcome("Runoob")
w = 4
h = 5
print("width =", w, " height =", h, " area =", area(w, h))

Welcome Runoob
width = 4  height = 5  area = 20


## 参数
以下是调用函数时可使用的正式参数类型：

必需参数

关键字参数

默认参数

不定长参数

### 必需参数
必需参数须以正确的顺序传入函数。调用时的数量必须和声明时的一样。

调用 printme() 函数，你必须传入一个参数，不然会出现语法错误：

In [53]:
#可写函数说明
def printme( str ):
    "打印任何传入的字符串"
    print (str)
    return
 
# 调用 printme 函数，不加参数会报错
printme()

TypeError: printme() missing 1 required positional argument: 'str'

### 关键字参数
关键字参数和函数调用关系紧密，函数调用使用关键字参数来确定传入的参数值。

In [84]:
#可写函数说明
def printinfo( name, age ):
    "打印任何传入的字符串"
    print ("名字: ", name)
    print ("年龄: ", age)
    return
 
#调用printinfo函数
printinfo( age=50, name="Jack" )

名字:  Jack
年龄:  50


### 默认参数
调用函数时，如果没有传递参数，则会使用默认参数。以下实例中如果没有传入 age 参数，则使用默认值：

In [85]:
#可写函数说明
def printinfo( name, age = 35 ):
    "打印任何传入的字符串"
    print ("名字: ", name)
    print ("年龄: ", age)
    return
 
#调用printinfo函数
printinfo( age=50, name="Jack" )
print ("------------------------")
printinfo( name="Jack" )

名字:  Jack
年龄:  50
------------------------
名字:  Jack
年龄:  35


### 不定长参数

加了星号 * 的参数会以元组(tuple)的形式导入，存放所有未命名的变量参数。

In [61]:
# 可写函数说明
def printinfo( arg1, *vartuple ):
    "打印任何传入的参数"
    print ("输出: ")
    print (arg1)
    print (vartuple)
    
# 调用printinfo 函数
printinfo( 70, 60, 50 )
print ("------------------------")
printinfo(70, 60, 50, 40)

输出: 
70
(60, 50)
------------------------
输出: 
70
(60, 50, 40)


## 匿名函数
python 使用 lambda 来创建匿名函数。

所谓匿名，意即不再使用 def 语句这样标准的形式定义一个函数。

In [62]:
# 可写函数说明
sum = lambda arg1, arg2: arg1 + arg2
 
# 调用sum函数
print ("相加后的值为 : ", sum( 10, 20 ))
print ("相加后的值为 : ", sum( 20, 20 ))

相加后的值为 :  30
相加后的值为 :  40


## return语句
return [表达式] 语句用于退出函数，选择性地向调用方返回一个表达式。

In [63]:
# 可写函数说明
def sum( arg1, arg2 ):
   # 返回2个参数的和."
    total = arg1 + arg2
    print ("函数内 : ", total)
    return total
 
# 调用sum函数
total = sum( 10, 20 )
print ("函数外 : ", total)

函数内 :  30
函数外 :  30


# Python 模块

在前面的几个章节中我们脚本上是用 python 解释器来编程，如果你从 Python 解释器退出再进入，那么你定义的所有的方法和变量就都消失了。
为此 Python 提供了一个办法，把这些定义存放在文件中，为一些脚本或者交互式的解释器实例使用，这个文件被称为模块。
模块是一个包含所有你定义的函数和变量的文件，其后缀名是.py。模块可以被别的程序引入，以使用该模块中的函数等功能。这也是使用 python 标准库的方法。

## import 语句

想使用 Python 源文件，只需在另一个源文件里执行 import 语句。(Sypder中演示）

## from … import 语句

Python 的 from 语句让你从模块中导入一个指定的部分到当前命名空间中。（Spyder中演示）

## from … import * 语句

把一个模块的所有内容全都导入到当前的命名空间也是可行的，只需使用如下声明：

from modname import *

## \__name__属性

一个模块被另一个程序第一次引入时，其主程序将运行。如果我们想在模块被引入时，模块中的某一程序块不执行，我们可以用__name__属性来使该程序块仅在该模块自身运行时执行。(Spyder中演示)

## 标准模块
Python 本身带着一些标准的模块库，在 Python 库参考文档中将会介绍到（就是后面的"库参考文档"）。

https://docs.python.org/zh-cn/3/library/index.html#library-index

# NumPy

## NumPy(Numerical Python) 是 Python 语言的一个扩展程序库，支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。

## NumPy Ndarray 对象

### NumPy 最重要的一个特点是其 N 维数组对象 ndarray，它是一系列同类型数据的集合，以 0 下标为开始进行集合中元素的索引。

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)  #subok:默认返回一个与基类类型一致的数组 ndmin:指定生成数组的最小维度

In [6]:
import numpy as np 
a = np.array([1,2,3])  
print (a)

[1 2 3]


In [4]:
# 多于一个维度  
import numpy as np 
a = np.array([[1,  2],  [3,  4]])  
print (a)

[[1 2]
 [3 4]]
int64


In [5]:
# dtype 参数  
import numpy as np 
a = np.array([1,  2,  3], dtype = complex)  
print (a)

[1.+0.j 2.+0.j 3.+0.j]
1


## numpy 支持的数据类型比 Python 内置的类型要多很多，基本上可以和 C 语言的数据类型对应上，其中部分类型对应为 Python 内置的类型。

![jupyter](./3.png)

## NumPy 数组属性

![jupyter](./4.png)

### ndarray.ndim
ndarray.ndim 用于返回数组的维数，等于秩。

In [14]:
import numpy as np 
 
a = np.arange(24) 
print(a)
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,12)
print(b)# b 现在拥有二个维度
print (b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
2


### ndarray.shape
ndarray.shape 表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即 ndim 属性(秩)。比如，一个二维数组，其维度表示"行数"和"列数"。
ndarray.shape 也可以用于调整数组大小。

In [13]:
import numpy as np  
 
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)

(2, 3)


In [14]:
import numpy as np 
 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape =  (3,2)  
print (a)

[[1 2]
 [3 4]
 [5 6]]


## NumPy创建数组

### numpy.empty
numpy.empty 方法用来创建一个指定形状（shape）、数据类型（dtype）且未初始化的数组：

numpy.empty(shape, dtype = float, order = 'C') #数组形状，数据类型，可选， 有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。

In [41]:
import numpy as np 
x = np.empty([4,2], dtype = int) 
print (x)

[[-4611686018427387904 -4611686018427387904]
 [                   4                    0]
 [                   0                    0]
 [-6917520265885185843     1134661662738549]]


### numpy.zeros
创建指定大小的数组，数组元素以 0 来填充：

numpy.zeros(shape, dtype = float, order = 'C')

In [9]:
import numpy as np
 
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5), dtype = np.int) 
print(y)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


### numpy.ones
创建指定形状的数组，数组元素以 1 来填充：

numpy.ones(shape, dtype = None, order = 'C')

In [10]:
import numpy as np
 
# 默认为浮点数
x = np.ones(5) 
print(x)
 
# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


## NumPy 从已有的数组创建数组

### numpy.asarray
numpy.asarray 类似 numpy.array，但 numpy.asarray 参数只有三个，比 numpy.array 少两个。

numpy.asarray(a, dtype = None, order = None)

In [15]:
import numpy as np 
 
x =  [1,2,3] 
a = np.asarray(x)  
print (a)

[1 2 3]


In [18]:
import numpy as np 
 
x =  [1,2,3] 
a = np.asarray(x, dtype =  float)  
print (a)

[1. 2. 3.]


## NumPy 从数值范围创建数组

### numpy.arange
numpy 包中的使用 arange 函数创建数值范围并返回 ndarray 对象，函数格式如下：

numpy.arange(start, stop, step, dtype)

In [19]:
import numpy as np
 
x = np.arange(5)  
print (x)

[0 1 2 3 4]


In [20]:
import numpy as np
 
# 设置了 dtype
x = np.arange(5, dtype =  float)  
print (x)

[0. 1. 2. 3. 4.]


In [21]:
import numpy as np
x = np.arange(10,20,2)  
print (x)

[10 12 14 16 18]


### numpy.linspace
numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None) #endpoint:该值为 true 时，数列中包含stop值，反之不包含，默认是True。
                                                                                                          #retstep:如果为 True 时，生成的数组中会显示间距，反之不显示。

In [23]:
import numpy as np
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [24]:
import numpy as np
a = np.linspace(1,1,10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
import numpy as np
 
a = np.linspace(10, 20,  5, endpoint =  False)  
print(a)

[10. 12. 14. 16. 18.]


## NumPy 切片和索引
ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。
ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。

In [26]:
import numpy as np
 
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])

[2 4 6]


In [27]:
import numpy as np
 
a = np.arange(10)  
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[2 4 6]


In [28]:
import numpy as np
 
a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
b = a[5] 
print(b)

5


In [29]:
import numpy as np
 
a = np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [30]:
import numpy as np
 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
# 从某个索引处开始切割
print('从数组索引 a[1:] 处开始切割')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引 a[1:] 处开始切割
[[3 4 5]
 [4 5 6]]


## NumPy 广播(Broadcast)
广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在相应的元素上进行。
如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的长度相同。

In [49]:
import numpy as np 
 
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。如：

In [56]:
import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


### 广播的规则:
让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。

输出数组的形状是输入数组形状的各个维度上的最大值。


## NumPy 迭代数组
NumPy 迭代器对象 numpy.nditer 提供了一种灵活访问一个或者多个数组元素的方式。

迭代器最基本的任务的可以完成对数组元素的访问。

In [61]:
import numpy as np
 
a = np.arange(6).reshape(2,3)
print ('原始数组是：')
print (a)
print ('\n')
print ('迭代输出元素：')
for x in np.nditer(a):
    print (x, end="," )
print ('\n')

原始数组是：
[[0 1 2]
 [3 4 5]]


迭代输出元素：
0,1,2,3,4,5,



In [63]:
import numpy as np
 
a = np.arange(6).reshape(2,3)
for x in np.nditer(a.T):
    print (x, end=", " )
print ('\n')
print(a.T)


0, 1, 2, 3, 4, 5, 

[[0 3]
 [1 4]
 [2 5]]


### 控制遍历顺序
for x in np.nditer(a, order='F'):Fortran order，即是列序优先；

for x in np.nditer(a.T, order='C'):C order，即是行序优先；

In [35]:
import numpy as np
 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：') 
print (a) 
print ('\n') 
print ('原始数组的转置是：') 
b = a.T 
print (b) 
print ('\n') 
print ('以 C 风格顺序排序：') 
c = b.copy(order='C')  
print (c)
for x in np.nditer(c):  
    print (x, end=", " )
print  ('\n') 
print  ('以 F 风格顺序排序：')
c = b.copy(order='F')  
print (c)
for x in np.nditer(c):  
    print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


原始数组的转置是：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


以 C 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

以 F 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [36]:
import numpy as np 
 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
print ('以 C 风格顺序排序：')
for x in np.nditer(a, order =  'C'):  
    print (x, end=", " )
print ('\n')
print ('以 F 风格顺序排序：')
for x in np.nditer(a, order =  'F'):  
    print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


以 C 风格顺序排序：
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

以 F 风格顺序排序：
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

### 广播迭代
如果两个数组是可广播的，nditer 组合对象能够同时迭代它们。 假设数组 a 的维度为 3X4，数组 b 的维度为 1X4 ，则使用以下迭代器（数组 b 被广播到 a 的大小）。

In [37]:
import numpy as np 
 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print  ('第一个数组为：')
print (a)
print  ('\n')
print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)  
print (b)
print ('\n')
print ('修改后的数组为：')
for x,y in np.nditer([a,b]):  
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组为：
[1 2 3 4]


修改后的数组为：
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 